---

- name: Installing packages using ansible
  hosts: all
  tasks:
      - name: Installing packages using alternative method
        yum:
           name: "{{item}}"
           state: present   
      
        with_items: 
             - docker
             - httpd
             - wget 
           
