---

- name: creating an users
  hosts: dev
  tasks:
       - name: creating muliple users using ansible loops
         user:
              name: "{{item}}"
              state: present
        
         with_items:

             - cricket
             - football
            
