---

- name: uninstalling packages and stopping service
  hosts: dev
  tasks:
      - name: unInstalling the package
        yum:
          name: httpd
          state: absent


      - name: services need to stop and disable
        service: 
               name: httpd
               state: stopped
               enabled: no


